import { BaseCalendarProvider } from './base';
import { RawJainEvent, Sect } from '../types';

export class DigambarReferenceProvider extends BaseCalendarProvider {
  name = 'digambar_panchang_reference';
  sect: Sect = 'Digambar';

  // Full 12-Month Digambar Panchang Tithi & Event Reference Dataset for 2026
  async fetchMonth(year: number, month: number): Promise<RawJainEvent[]> {
    if (year !== 2026) return [];

    const fullYearEvents: Record<number, RawJainEvent[]> = {
      1: [
        { title: 'Rohini Vrat', sect: 'Digambar', category: 'Festival', tag: 'Vrat', day: 1, month: 1, year: 2026, source: this.name },
        { title: 'Shree Abhinandan Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Gyan Kalyanak', day: 2, month: 1, year: 2026, source: this.name },
        { title: 'Shukla Chaturdashi', sect: 'Digambar', category: 'Parv', tag: 'Chaturdashi', day: 2, month: 1, year: 2026, source: this.name },
        { title: 'Shodashkaran Vrat Prarambh', sect: 'Digambar', category: 'Festival', tag: 'Vrat', day: 2, month: 1, year: 2026, source: this.name },
        { title: 'Shree Dharmanath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Gyan Kalyanak', day: 3, month: 1, year: 2026, source: this.name },
        { title: 'Shree Padmaprabh Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Garbh Kalyanak', day: 8, month: 1, year: 2026, source: this.name },
        { title: 'Krishna Ashtami', sect: 'Digambar', category: 'Parv', tag: 'Ashtami', day: 11, month: 1, year: 2026, source: this.name },
        { title: 'Devdarshan Divas', sect: 'Digambar', category: 'Festival', tag: 'Festival', day: 14, month: 1, year: 2026, source: this.name },
        { title: 'Shree Shitalnath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Janma + Tap Kalyanak', day: 15, month: 1, year: 2026, source: this.name },
        { title: 'Shree Rushabhdev Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Moksha Kalyanak', day: 17, month: 1, year: 2026, source: this.name },
        { title: 'Krishna Chaturdashi', sect: 'Digambar', category: 'Parv', tag: 'Chaturdashi', day: 17, month: 1, year: 2026, source: this.name },
        { title: 'Shree Adinath Bhagwan Moksha Divas', sect: 'Digambar', category: 'Festival', tag: 'Festival', day: 17, month: 1, year: 2026, source: this.name },
        { title: 'Shree Shreyansnath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Gyan Kalyanak', day: 18, month: 1, year: 2026, source: this.name },
        { title: 'Labdhi Vidhan Vrat Prarambh', sect: 'Digambar', category: 'Festival', tag: 'Vrat', day: 19, month: 1, year: 2026, source: this.name },
        { title: 'Shree Vasupujya Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Gyan Kalyanak', day: 20, month: 1, year: 2026, source: this.name },
        { title: 'Labdhi Vidhan Vrat Purn', sect: 'Digambar', category: 'Festival', tag: 'Vrat', day: 21, month: 1, year: 2026, source: this.name },
        { title: 'Shree Vimalnath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Janma + Tap Kalyanak', day: 22, month: 1, year: 2026, source: this.name },
        { title: 'Das Lakshan Vrat Prarambh', sect: 'Digambar', category: 'Festival', tag: 'Vrat', day: 22, month: 1, year: 2026, source: this.name },
        { title: 'Pushpanjali Vrat Prarambh', sect: 'Digambar', category: 'Festival', tag: 'Vrat', day: 23, month: 1, year: 2026, source: this.name },
        { title: 'Shree Vimalnath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Gyan Kalyanak', day: 24, month: 1, year: 2026, source: this.name },
        { title: 'Shukla Ashtami', sect: 'Digambar', category: 'Parv', tag: 'Ashtami', day: 26, month: 1, year: 2026, source: this.name },
        { title: 'Shree Ajitnath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Tap Kalyanak', day: 27, month: 1, year: 2026, source: this.name },
        { title: 'Pushpanjali Vrat Purn', sect: 'Digambar', category: 'Festival', tag: 'Vrat', day: 27, month: 1, year: 2026, source: this.name },
        { title: 'Shree Ajitnath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Janma Kalyanak', day: 28, month: 1, year: 2026, source: this.name },
        { title: 'Rohini Vrat', sect: 'Digambar', category: 'Festival', tag: 'Vrat', day: 29, month: 1, year: 2026, source: this.name },
        { title: 'Shree Abhinandan Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Janma + Tap Kalyanak', day: 30, month: 1, year: 2026, source: this.name },
        { title: 'Shree Dharmanath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Janma + Tap Kalyanak', day: 30, month: 1, year: 2026, source: this.name },
        { title: 'Ratnatray Vrat Prarambh', sect: 'Digambar', category: 'Festival', tag: 'Vrat', day: 30, month: 1, year: 2026, source: this.name },
        { title: 'Shukla Chaturdashi', sect: 'Digambar', category: 'Parv', tag: 'Chaturdashi', day: 31, month: 1, year: 2026, source: this.name },
        { title: 'Das Lakshan Vrat Purn', sect: 'Digambar', category: 'Festival', tag: 'Vrat', day: 31, month: 1, year: 2026, source: this.name },
      ],
      2: [
        { title: 'Shodashkaran Vrat Purn', sect: 'Digambar', category: 'Festival', tag: 'Vrat', day: 2, month: 2, year: 2026, source: this.name },
        { title: 'Shree Padmaprabh Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Moksha Kalyanak', day: 5, month: 2, year: 2026, source: this.name },
        { title: 'Shree Suparshvanath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Gyan Kalyanak', day: 7, month: 2, year: 2026, source: this.name },
        { title: 'Shree Suparshvanath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Moksha Kalyanak', day: 8, month: 2, year: 2026, source: this.name },
        { title: 'Shree Chandraprabh Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Gyan + Moksha Kalyanak', day: 8, month: 2, year: 2026, source: this.name },
        { title: 'Krishna Ashtami', sect: 'Digambar', category: 'Parv', tag: 'Ashtami', day: 9, month: 2, year: 2026, source: this.name },
        { title: 'Shree Pushpadant Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Garbh Kalyanak', day: 10, month: 2, year: 2026, source: this.name },
        { title: 'Shree Rushabhdev Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Gyan Kalyanak', day: 13, month: 2, year: 2026, source: this.name },
        { title: 'Shree Shreyansnath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Janma + Tap Kalyanak', day: 13, month: 2, year: 2026, source: this.name },
        { title: 'Shree Munisuvrat Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Moksha Kalyanak', day: 14, month: 2, year: 2026, source: this.name },
        { title: 'Shree Vasupujya Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Janma + Tap Kalyanak', day: 16, month: 2, year: 2026, source: this.name },
        { title: 'Krishna Chaturdashi', sect: 'Digambar', category: 'Parv', tag: 'Chaturdashi', day: 16, month: 2, year: 2026, source: this.name },
        { title: 'Shree Arahnath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Garbh Kalyanak', day: 20, month: 2, year: 2026, source: this.name },
        { title: 'Shree Mallinath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Moksha Kalyanak', day: 22, month: 2, year: 2026, source: this.name },
        { title: 'Shree Chandraprabh Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Moksha Kalyanak', day: 23, month: 2, year: 2026, source: this.name },
        { title: 'Shree Sambhavnath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Garbh Kalyanak', day: 24, month: 2, year: 2026, source: this.name },
        { title: 'Shukla Ashtami', sect: 'Digambar', category: 'Parv', tag: 'Ashtami', day: 24, month: 2, year: 2026, source: this.name },
        { title: 'Rohini Vrat', sect: 'Digambar', category: 'Festival', tag: 'Vrat', day: 25, month: 2, year: 2026, source: this.name },
      ],
      3: [
        { title: 'Shukla Chaturdashi', sect: 'Digambar', category: 'Parv', tag: 'Chaturdashi', day: 2, month: 3, year: 2026, source: this.name },
        { title: 'Shodashkaran Vrat Prarambh', sect: 'Digambar', category: 'Festival', tag: 'Vrat', day: 2, month: 3, year: 2026, source: this.name },
        { title: 'Ashtanika Vrat Purn', sect: 'Digambar', category: 'Festival', tag: 'Vrat', day: 3, month: 3, year: 2026, source: this.name },
        { title: 'Shree Parshvanath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Gyan Kalyanak', day: 7, month: 3, year: 2026, source: this.name },
        { title: 'Shree Chandraprabh Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Garbh Kalyanak', day: 8, month: 3, year: 2026, source: this.name },
        { title: 'Shree Shitalnath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Garbh Kalyanak', day: 11, month: 3, year: 2026, source: this.name },
        { title: 'Krishna Ashtami', sect: 'Digambar', category: 'Parv', tag: 'Ashtami', day: 11, month: 3, year: 2026, source: this.name },
        { title: 'Shree Rushabhdev Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Janma + Tap Kalyanak', day: 12, month: 3, year: 2026, source: this.name },
        { title: 'Tirthankar Divas', sect: 'Digambar', category: 'Festival', tag: 'Festival', day: 12, month: 3, year: 2026, source: this.name },
        { title: 'Shree Anantnath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Gyan + Moksha Kalyanak', day: 18, month: 3, year: 2026, source: this.name },
        { title: 'Shree Arahnath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Moksha Kalyanak', day: 18, month: 3, year: 2026, source: this.name },
        { title: 'Krishna Chaturdashi', sect: 'Digambar', category: 'Parv', tag: 'Chaturdashi', day: 18, month: 3, year: 2026, source: this.name },
        { title: 'Shree Mallinath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Garbh Kalyanak', day: 19, month: 3, year: 2026, source: this.name },
        { title: 'Labdhi Vidhan Vrat Prarambh', sect: 'Digambar', category: 'Festival', tag: 'Vrat', day: 19, month: 3, year: 2026, source: this.name },
        { title: 'Shree Kunthunath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Gyan Kalyanak', day: 21, month: 3, year: 2026, source: this.name },
        { title: 'Labdhi Vidhan Vrat Purn', sect: 'Digambar', category: 'Festival', tag: 'Vrat', day: 21, month: 3, year: 2026, source: this.name },
        { title: 'Das Lakshan Vrat Prarambh', sect: 'Digambar', category: 'Festival', tag: 'Vrat', day: 22, month: 3, year: 2026, source: this.name },
        { title: 'Shree Ajitnath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Moksha Kalyanak', day: 23, month: 3, year: 2026, source: this.name },
        { title: 'Pushpanjali Vrat Prarambh', sect: 'Digambar', category: 'Festival', tag: 'Vrat', day: 23, month: 3, year: 2026, source: this.name },
        { title: 'Shree Sambhavnath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Moksha Kalyanak', day: 24, month: 3, year: 2026, source: this.name },
        { title: 'Rohini Vrat', sect: 'Digambar', category: 'Festival', tag: 'Vrat', day: 24, month: 3, year: 2026, source: this.name },
        { title: 'Shukla Ashtami', sect: 'Digambar', category: 'Parv', tag: 'Ashtami', day: 26, month: 3, year: 2026, source: this.name },
        { title: 'Pushpanjali Vrat Purn', sect: 'Digambar', category: 'Festival', tag: 'Vrat', day: 27, month: 3, year: 2026, source: this.name },
        { title: 'Shree Sumatinath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Janma + Gyan + Moksha', day: 28, month: 3, year: 2026, source: this.name },
        { title: 'Shree Mahavir Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Janma Kalyanak', day: 30, month: 3, year: 2026, source: this.name },
        { title: 'Ratnatray Vrat Prarambh', sect: 'Digambar', category: 'Festival', tag: 'Vrat', day: 30, month: 3, year: 2026, source: this.name },
        { title: 'Mahavir Jayanti (Janma Divas)', sect: 'Digambar', category: 'Festival', tag: 'Festival', day: 30, month: 3, year: 2026, source: this.name },
        { title: 'Shukla Chaturdashi', sect: 'Digambar', category: 'Parv', tag: 'Chaturdashi', day: 31, month: 3, year: 2026, source: this.name },
        { title: 'Das Lakshan Vrat Purn', sect: 'Digambar', category: 'Festival', tag: 'Vrat', day: 31, month: 3, year: 2026, source: this.name },
      ],
      4: [
        { title: 'Shree Padmaprabh Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Gyan Kalyanak', day: 1, month: 4, year: 2026, source: this.name },
        { title: 'Ratnatray Vrat Purn', sect: 'Digambar', category: 'Festival', tag: 'Vrat', day: 1, month: 4, year: 2026, source: this.name },
        { title: 'Shodashkaran Vrat Purn', sect: 'Digambar', category: 'Festival', tag: 'Vrat', day: 2, month: 4, year: 2026, source: this.name },
        { title: 'Shree Parshvanath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Garbh Kalyanak', day: 4, month: 4, year: 2026, source: this.name },
        { title: 'Krishna Ashtami', sect: 'Digambar', category: 'Parv', tag: 'Ashtami', day: 10, month: 4, year: 2026, source: this.name },
        { title: 'Shree Munisuvrat Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Gyan Kalyanak', day: 11, month: 4, year: 2026, source: this.name },
        { title: 'Shree Munisuvrat Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Janma + Tap Kalyanak', day: 12, month: 4, year: 2026, source: this.name },
        { title: 'Shree Dharmanath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Garbh Kalyanak', day: 15, month: 4, year: 2026, source: this.name },
        { title: 'Shree Naminath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Moksha Kalyanak', day: 16, month: 4, year: 2026, source: this.name },
        { title: 'Krishna Chaturdashi', sect: 'Digambar', category: 'Parv', tag: 'Chaturdashi', day: 16, month: 4, year: 2026, source: this.name },
        { title: 'Shree Kunthunath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Janma + Tap + Moksha', day: 18, month: 4, year: 2026, source: this.name },
        { title: 'Akshay Tritiya (Rushabhdev Bhagwan Aahar din)', sect: 'Digambar', category: 'Festival', tag: 'Festival', day: 19, month: 4, year: 2026, source: this.name },
        { title: 'Rohini Vrat', sect: 'Digambar', category: 'Festival', tag: 'Vrat', day: 20, month: 4, year: 2026, source: this.name },
        { title: 'Shree Abhinandan Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Garbh + Moksha', day: 22, month: 4, year: 2026, source: this.name },
        { title: 'Shukla Ashtami', sect: 'Digambar', category: 'Parv', tag: 'Ashtami', day: 24, month: 4, year: 2026, source: this.name },
        { title: 'Shree Sumatinath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Tap Kalyanak', day: 25, month: 4, year: 2026, source: this.name },
        { title: 'Shree Mahavir Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Gyan Kalyanak', day: 26, month: 4, year: 2026, source: this.name },
        { title: 'Shukla Chaturdashi', sect: 'Digambar', category: 'Parv', tag: 'Chaturdashi', day: 30, month: 4, year: 2026, source: this.name },
      ],
      5: [
        { title: 'Shree Shreyansnath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Garbh Kalyanak', day: 8, month: 5, year: 2026, source: this.name },
        { title: 'Krishna Ashtami', sect: 'Digambar', category: 'Parv', tag: 'Ashtami', day: 10, month: 5, year: 2026, source: this.name },
        { title: 'Shree Vimalnath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Garbh Kalyanak', day: 12, month: 5, year: 2026, source: this.name },
        { title: 'Shree Anantnath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Janma + Tap Kalyanak', day: 14, month: 5, year: 2026, source: this.name },
        { title: 'Shree Shantinath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Janma + Tap + Moksha', day: 15, month: 5, year: 2026, source: this.name },
        { title: 'Krishna Chaturdashi', sect: 'Digambar', category: 'Parv', tag: 'Chaturdashi', day: 15, month: 5, year: 2026, source: this.name },
        { title: 'Shanti Dhara Divas', sect: 'Digambar', category: 'Festival', tag: 'Festival', day: 15, month: 5, year: 2026, source: this.name },
        { title: 'Shree Ajitnath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Garbh Kalyanak', day: 16, month: 5, year: 2026, source: this.name },
        { title: 'Adhik Maas Prarambh', sect: 'Digambar', category: 'Festival', tag: 'Festival', day: 17, month: 5, year: 2026, source: this.name },
        { title: 'Rohini Vrat', sect: 'Digambar', category: 'Festival', tag: 'Vrat', day: 18, month: 5, year: 2026, source: this.name },
        { title: 'Shukla Ashtami', sect: 'Digambar', category: 'Parv', tag: 'Ashtami', day: 23, month: 5, year: 2026, source: this.name },
        { title: 'Shukla Chaturdashi', sect: 'Digambar', category: 'Parv', tag: 'Chaturdashi', day: 30, month: 5, year: 2026, source: this.name },
      ],
      6: [
        { title: 'Krishna Ashtami', sect: 'Digambar', category: 'Parv', tag: 'Ashtami', day: 8, month: 6, year: 2026, source: this.name },
        { title: 'Krishna Chaturdashi', sect: 'Digambar', category: 'Parv', tag: 'Chaturdashi', day: 14, month: 6, year: 2026, source: this.name },
        { title: 'Rohini Vrat', sect: 'Digambar', category: 'Festival', tag: 'Vrat', day: 14, month: 6, year: 2026, source: this.name },
        { title: 'Adhik Maas Samapt', sect: 'Digambar', category: 'Festival', tag: 'Festival', day: 15, month: 6, year: 2026, source: this.name },
        { title: 'Shree Dharmanath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Moksha Kalyanak', day: 18, month: 6, year: 2026, source: this.name },
        { title: 'Shrut Panchami (Jinvani Divas)', sect: 'Digambar', category: 'Festival', tag: 'Festival', day: 19, month: 6, year: 2026, source: this.name },
        { title: 'Shukla Ashtami', sect: 'Digambar', category: 'Parv', tag: 'Ashtami', day: 22, month: 6, year: 2026, source: this.name },
        { title: 'Shree Suparshvanath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Janma + Tap Kalyanak', day: 26, month: 6, year: 2026, source: this.name },
        { title: 'Shukla Chaturdashi', sect: 'Digambar', category: 'Parv', tag: 'Chaturdashi', day: 28, month: 6, year: 2026, source: this.name },
      ],
      7: [
        { title: 'Shree Rushabhdev Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Garbh Kalyanak', day: 2, month: 7, year: 2026, source: this.name },
        { title: 'Shree Vasupujya Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Garbh Kalyanak', day: 6, month: 7, year: 2026, source: this.name },
        { title: 'Shree Vimalnath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Moksha Kalyanak', day: 8, month: 7, year: 2026, source: this.name },
        { title: 'Krishna Ashtami', sect: 'Digambar', category: 'Parv', tag: 'Ashtami', day: 8, month: 7, year: 2026, source: this.name },
        { title: 'Shree Naminath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Janma + Tap Kalyanak', day: 9, month: 7, year: 2026, source: this.name },
        { title: 'Rohini Vrat', sect: 'Digambar', category: 'Festival', tag: 'Vrat', day: 12, month: 7, year: 2026, source: this.name },
        { title: 'Krishna Chaturdashi', sect: 'Digambar', category: 'Parv', tag: 'Chaturdashi', day: 13, month: 7, year: 2026, source: this.name },
        { title: 'Rishi Panchami', sect: 'Digambar', category: 'Festival', tag: 'Festival', day: 18, month: 7, year: 2026, source: this.name },
        { title: 'Shree Mahavir Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Garbh Kalyanak', day: 19, month: 7, year: 2026, source: this.name },
        { title: 'Shree Neminath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Moksha Kalyanak', day: 20, month: 7, year: 2026, source: this.name },
        { title: 'Namokar Paintisi Vrat Prarambh', sect: 'Digambar', category: 'Festival', tag: 'Vrat', day: 20, month: 7, year: 2026, source: this.name },
        { title: 'Shukla Ashtami', sect: 'Digambar', category: 'Parv', tag: 'Ashtami', day: 21, month: 7, year: 2026, source: this.name },
        { title: 'Ashtanika Vrat Prarambh', sect: 'Digambar', category: 'Festival', tag: 'Vrat', day: 21, month: 7, year: 2026, source: this.name },
        { title: 'Ravi Vrat', sect: 'Digambar', category: 'Festival', tag: 'Vrat', day: 26, month: 7, year: 2026, source: this.name },
        { title: 'Shukla Chaturdashi', sect: 'Digambar', category: 'Parv', tag: 'Chaturdashi', day: 28, month: 7, year: 2026, source: this.name },
        { title: 'Chaturmaas Prarambh (Kalash Sthapna)', sect: 'Digambar', category: 'Festival', tag: 'Festival', day: 28, month: 7, year: 2026, source: this.name },
        { title: 'Karma Nirjara Vrat', sect: 'Digambar', category: 'Festival', tag: 'Vrat', day: 28, month: 7, year: 2026, source: this.name },
        { title: 'Ashtanika Vrat Purn', sect: 'Digambar', category: 'Festival', tag: 'Vrat', day: 29, month: 7, year: 2026, source: this.name },
        { title: 'Veer Shasan Jayanti / Yug Parivartan Divas', sect: 'Digambar', category: 'Festival', tag: 'Festival', day: 30, month: 7, year: 2026, source: this.name },
        { title: 'Shree Munisuvrat Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Garbh Kalyanak', day: 31, month: 7, year: 2026, source: this.name },
        { title: 'Ratnavali / Ekavali / Dwikavali Vrat', sect: 'Digambar', category: 'Festival', tag: 'Vrat', day: 31, month: 7, year: 2026, source: this.name },
      ],
      8: [
        { title: 'Krishna Ashtami', sect: 'Digambar', category: 'Parv', tag: 'Ashtami', day: 6, month: 8, year: 2026, source: this.name },
        { title: 'Shree Kunthunath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Garbh Kalyanak', day: 8, month: 8, year: 2026, source: this.name },
        { title: 'Rohini Vrat', sect: 'Digambar', category: 'Festival', tag: 'Vrat', day: 9, month: 8, year: 2026, source: this.name },
        { title: 'Krishna Chaturdashi', sect: 'Digambar', category: 'Parv', tag: 'Chaturdashi', day: 11, month: 8, year: 2026, source: this.name },
        { title: 'Shree Sumatinath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Garbh Kalyanak', day: 14, month: 8, year: 2026, source: this.name },
        { title: 'Shree Neminath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Janma + Tap Kalyanak', day: 18, month: 8, year: 2026, source: this.name },
        { title: 'Shree Parshvanath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Moksha Kalyanak', day: 19, month: 8, year: 2026, source: this.name },
        { title: 'Shukla Ashtami', sect: 'Digambar', category: 'Parv', tag: 'Ashtami', day: 20, month: 8, year: 2026, source: this.name },
        { title: 'Shukla Chaturdashi', sect: 'Digambar', category: 'Parv', tag: 'Chaturdashi', day: 27, month: 8, year: 2026, source: this.name },
        { title: 'Shree Shreyansnath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Moksha Kalyanak', day: 28, month: 8, year: 2026, source: this.name },
        { title: 'Raksha Bandhan (Vishnukumar Muni)', sect: 'Digambar', category: 'Festival', tag: 'Festival', day: 28, month: 8, year: 2026, source: this.name },
      ],
      9: [
        { title: 'Shree Shantinath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Garbh Kalyanak', day: 3, month: 9, year: 2026, source: this.name },
        { title: 'Krishna Ashtami', sect: 'Digambar', category: 'Parv', tag: 'Ashtami', day: 4, month: 9, year: 2026, source: this.name },
        { title: 'Janmashtami', sect: 'Digambar', category: 'Festival', tag: 'Festival', day: 4, month: 9, year: 2026, source: this.name },
        { title: 'Rohini Vrat', sect: 'Digambar', category: 'Festival', tag: 'Vrat', day: 6, month: 9, year: 2026, source: this.name },
        { title: 'Krishna Chaturdashi', sect: 'Digambar', category: 'Parv', tag: 'Chaturdashi', day: 10, month: 9, year: 2026, source: this.name },
        { title: 'Sola Kaaran Vrat Prarambh', sect: 'Digambar', category: 'Festival', tag: 'Vrat', day: 13, month: 9, year: 2026, source: this.name },
        { title: 'Labdhi Vidhan Vrat Prarambh', sect: 'Digambar', category: 'Festival', tag: 'Vrat', day: 14, month: 9, year: 2026, source: this.name },
        { title: 'Das Lakshan Paryushan Prarambh (Uttam Kshama)', sect: 'Digambar', category: 'Festival', tag: 'Festival', day: 15, month: 9, year: 2026, source: this.name },
        { title: 'Shree Suparshvanath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Garbh Kalyanak', day: 17, month: 9, year: 2026, source: this.name },
        { title: 'Shree Pushpadant Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Moksha Kalyanak', day: 19, month: 9, year: 2026, source: this.name },
        { title: 'Shukla Ashtami', sect: 'Digambar', category: 'Parv', tag: 'Ashtami', day: 19, month: 9, year: 2026, source: this.name },
        { title: 'Sugandh Dashami Vrat', sect: 'Digambar', category: 'Festival', tag: 'Vrat', day: 21, month: 9, year: 2026, source: this.name },
        { title: 'Ratnatray Vrat Prarambh', sect: 'Digambar', category: 'Festival', tag: 'Vrat', day: 22, month: 9, year: 2026, source: this.name },
        { title: 'Anant Vrat Prarambh', sect: 'Digambar', category: 'Festival', tag: 'Vrat', day: 24, month: 9, year: 2026, source: this.name },
        { title: 'Shree Vasupujya Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Moksha Kalyanak', day: 25, month: 9, year: 2026, source: this.name },
        { title: 'Shukla Chaturdashi', sect: 'Digambar', category: 'Parv', tag: 'Chaturdashi', day: 25, month: 9, year: 2026, source: this.name },
        { title: 'Anant Chaturdashi (Das Lakshan Samapt)', sect: 'Digambar', category: 'Festival', tag: 'Festival', day: 25, month: 9, year: 2026, source: this.name },
        { title: 'Kshama-vani Parva / Ratnatray Vrat Purn', sect: 'Digambar', category: 'Festival', tag: 'Festival', day: 26, month: 9, year: 2026, source: this.name },
        { title: 'Shree Naminath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Garbh Kalyanak', day: 28, month: 9, year: 2026, source: this.name },
      ],
      10: [
        { title: 'Rohini Vrat', sect: 'Digambar', category: 'Festival', tag: 'Vrat', day: 1, month: 10, year: 2026, source: this.name },
        { title: 'Krishna Ashtami', sect: 'Digambar', category: 'Parv', tag: 'Ashtami', day: 3, month: 10, year: 2026, source: this.name },
        { title: 'Krishna Chaturdashi', sect: 'Digambar', category: 'Parv', tag: 'Chaturdashi', day: 9, month: 10, year: 2026, source: this.name },
        { title: 'Shree Neminath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Gyan Kalyanak', day: 11, month: 10, year: 2026, source: this.name },
        { title: 'Shree Shitalnath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Moksha Kalyanak', day: 19, month: 10, year: 2026, source: this.name },
        { title: 'Shukla Ashtami', sect: 'Digambar', category: 'Parv', tag: 'Ashtami', day: 19, month: 10, year: 2026, source: this.name },
        { title: 'Vijayadashami (Dussehra)', sect: 'Digambar', category: 'Festival', tag: 'Festival', day: 21, month: 10, year: 2026, source: this.name },
        { title: 'Shukla Chaturdashi', sect: 'Digambar', category: 'Parv', tag: 'Chaturdashi', day: 25, month: 10, year: 2026, source: this.name },
        { title: 'Shree Anantnath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Garbh Kalyanak', day: 26, month: 10, year: 2026, source: this.name },
        { title: 'Shree Sambhavnath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Gyan Kalyanak', day: 29, month: 10, year: 2026, source: this.name },
      ],
      11: [
        { title: 'Krishna Ashtami', sect: 'Digambar', category: 'Parv', tag: 'Ashtami', day: 2, month: 11, year: 2026, source: this.name },
        { title: 'Shree Padmaprabh Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Janma + Tap Kalyanak', day: 7, month: 11, year: 2026, source: this.name },
        { title: 'Krishna Chaturdashi', sect: 'Digambar', category: 'Parv', tag: 'Chaturdashi', day: 8, month: 11, year: 2026, source: this.name },
        { title: 'Dhanteras (Mahavir Nirvana Laghu Divas)', sect: 'Digambar', category: 'Festival', tag: 'Festival', day: 8, month: 11, year: 2026, source: this.name },
        { title: 'Shree Mahavir Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Moksha Kalyanak', day: 9, month: 11, year: 2026, source: this.name },
        { title: 'Deepavali / Mahavir Nirvana / Gautam Swami Kevalgnan', sect: 'Digambar', category: 'Festival', tag: 'Festival', day: 9, month: 11, year: 2026, source: this.name },
        { title: 'Govardhan Puja / Nutan Varsh (Veer Nirvana Samvat 2553)', sect: 'Digambar', category: 'Festival', tag: 'Festival', day: 10, month: 11, year: 2026, source: this.name },
        { title: 'Shree Pushpadant Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Gyan Kalyanak', day: 11, month: 11, year: 2026, source: this.name },
        { title: 'Bhai Dooj', sect: 'Digambar', category: 'Festival', tag: 'Festival', day: 11, month: 11, year: 2026, source: this.name },
        { title: 'Gyan Panchami', sect: 'Digambar', category: 'Festival', tag: 'Festival', day: 14, month: 11, year: 2026, source: this.name },
        { title: 'Shree Neminath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Garbh Kalyanak', day: 15, month: 11, year: 2026, source: this.name },
        { title: 'Shukla Ashtami', sect: 'Digambar', category: 'Parv', tag: 'Ashtami', day: 17, month: 11, year: 2026, source: this.name },
        { title: 'Shree Arahnath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Gyan Kalyanak', day: 21, month: 11, year: 2026, source: this.name },
        { title: 'Shukla Chaturdashi', sect: 'Digambar', category: 'Parv', tag: 'Chaturdashi', day: 23, month: 11, year: 2026, source: this.name },
        { title: 'Shree Sambhavnath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Janma Kalyanak', day: 24, month: 11, year: 2026, source: this.name },
        { title: 'Kartik Purnima', sect: 'Digambar', category: 'Festival', tag: 'Festival', day: 24, month: 11, year: 2026, source: this.name },
        { title: 'Rohini Vrat', sect: 'Digambar', category: 'Festival', tag: 'Vrat', day: 25, month: 11, year: 2026, source: this.name },
      ],
      12: [
        { title: 'Krishna Ashtami', sect: 'Digambar', category: 'Parv', tag: 'Ashtami', day: 1, month: 12, year: 2026, source: this.name },
        { title: 'Shree Mahavir Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Tap Kalyanak', day: 3, month: 12, year: 2026, source: this.name },
        { title: 'Mukta-vali Vrat', sect: 'Digambar', category: 'Festival', tag: 'Vrat', day: 4, month: 12, year: 2026, source: this.name },
        { title: 'Krishna Chaturdashi', sect: 'Digambar', category: 'Parv', tag: 'Chaturdashi', day: 7, month: 12, year: 2026, source: this.name },
        { title: 'Shree Pushpadant Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Janma + Tap Kalyanak', day: 9, month: 12, year: 2026, source: this.name },
        { title: 'Mukta-vali Vrat', sect: 'Digambar', category: 'Festival', tag: 'Vrat', day: 12, month: 12, year: 2026, source: this.name },
        { title: 'Shukla Ashtami', sect: 'Digambar', category: 'Parv', tag: 'Ashtami', day: 17, month: 12, year: 2026, source: this.name },
        { title: 'Shree Arahnath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Tap Kalyanak', day: 19, month: 12, year: 2026, source: this.name },
        { title: 'Shree Mallinath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Janma + Tap Kalyanak', day: 20, month: 12, year: 2026, source: this.name },
        { title: 'Shree Naminath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Gyan Kalyanak', day: 20, month: 12, year: 2026, source: this.name },
        { title: 'Shree Sambhavnath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Tap Kalyanak', day: 23, month: 12, year: 2026, source: this.name },
        { title: 'Shree Arahnath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Janma Kalyanak', day: 23, month: 12, year: 2026, source: this.name },
        { title: 'Shukla Chaturdashi', sect: 'Digambar', category: 'Parv', tag: 'Chaturdashi', day: 23, month: 12, year: 2026, source: this.name },
        { title: 'Rohini Vrat', sect: 'Digambar', category: 'Festival', tag: 'Vrat', day: 23, month: 12, year: 2026, source: this.name },
        { title: 'Shree Mallinath Bhagwan', sect: 'Digambar', category: 'Kalyanak', tag: 'Gyan Kalyanak', day: 25, month: 12, year: 2026, source: this.name },
        { title: 'Krishna Ashtami', sect: 'Digambar', category: 'Parv', tag: 'Ashtami', day: 31, month: 12, year: 2026, source: this.name },
      ]
    };

    return fullYearEvents[month] || [];
  }
}
